language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  # fast_finish: true
cache: cargo
script:
  - cargo build --release --all
  - cargo test --all
  - cargo doc --release --no-deps

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  local-dir: target/doc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master

# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  file:
    - "target/release/esc"
    - "target/release/esi"
  on:
    tags: true

