(function() {var implementors = {};
implementors["ecmascript"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ecmascript/version/struct.ECMAScriptVersion.html\" title=\"struct ecmascript::version::ECMAScriptVersion\">ECMAScriptVersion</a>",synthetic:false,types:["ecmascript::version::ECMAScriptVersion"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ecmascript/ast/span/struct.LineColumn.html\" title=\"struct ecmascript::ast::span::LineColumn\">LineColumn</a>",synthetic:false,types:["ecmascript::ast::span::LineColumn"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ecmascript/vm/value/object/struct.DataPropertyDescriptor.html\" title=\"struct ecmascript::vm::value::object::DataPropertyDescriptor\">DataPropertyDescriptor</a>",synthetic:false,types:["ecmascript::vm::value::object::DataPropertyDescriptor"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ecmascript/vm/value/object/struct.AccessorPropertyDescriptor.html\" title=\"struct ecmascript::vm::value::object::AccessorPropertyDescriptor\">AccessorPropertyDescriptor</a>",synthetic:false,types:["ecmascript::vm::value::object::AccessorPropertyDescriptor"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"ecmascript/vm/value/object/enum.PropertyDescriptor.html\" title=\"enum ecmascript::vm::value::object::PropertyDescriptor\">PropertyDescriptor</a>",synthetic:false,types:["ecmascript::vm::value::object::PropertyDescriptor"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ecmascript/vm/value/object/struct.Property.html\" title=\"struct ecmascript::vm::value::object::Property\">Property</a>",synthetic:false,types:["ecmascript::vm::value::object::Property"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
